# Generated by Django 2.1.5 on 2019-02-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190128_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='open_street_map_url',
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='event',
            name='zoom',
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='organization',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
