# Generated by Django 2.1.5 on 2019-01-27 15:34

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.models.validate_user_email_not_exist, django.core.validators.EmailValidator()], verbose_name='email address'),
        ),
    ]
